### ISSUE TITLE
Cancel in-flight CI runs on PR updates

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/opensource#44]
Annoyingly, by default, pushing new commits to a PR will not cancel any current github actions that are running on previous commits, wasting resources and potentially stalling the actions on the new commit(s) from being run.

This can be fixed by adding the following to our action workflows.

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```
